The **`theme()` function** lets you control the non–data parts of a ggplot — things like titles, axis labels, legend placements, grid lines, and backgrounds.

While built-in themes give you quick presets, `theme()` provides full flexibility. Think of it as the _fine-tuning tool_ for your plot’s appearance. You can adjust individual elements, like an axis label or the background of the panel, to make your chart match your style or branding.

What if we want to change the panel background color? To do that, we address the corresponding element inside a `theme()` call:

```{r}
library(ggplot2)

# Basic scatterplot with custom panel background
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point(size = 3, color = "steelblue") +
  theme(
    panel.background = element_rect(fill = "#CEE5ED")
  )
```

Remember the _panel_ is the "data area" — the grey box in the default look. The full area is called the _plot_.

Tip: You can also start from a non-default complete theme, e.g., `theme_minimal()`, and then tweak individual elements with theme(). That way you don’t have to define everything from scratch 

# Anatomy of a Theme
The main building blocks of themes in ggplot2 are **theme elements**.

For example, to modify the background of the panel, you reference it using a hierarchy connected by `.` between levels. In this case, the element name is `panel.background`.

The value you assign to a theme element must be an **element function**. For the panel background, we use `element_rect()`, which is designed for elements drawn as rectangles.

`element_rect()` accepts several attributes, such as `fill`, `color`, and `linewidth`. To customize an attribute, simply provide a value for it.

# Going Down the Rabbit Hole
The `ggplot2` theme system is **hierarchical** and **cascading**: broader defaults flow “top-down,” and targeted tweaks override them where you set them. This lets you fine-tune specific parts of a plot without rewriting the whole theme.


The hierarchy is straightforward: start at a broad component and navigate down to the subcomponent you want to change. For example, use `panel.grid` to adjust all grid lines at once, or go deeper to `panel.grid.minor.y` to modify only minor horizontal grid lines.

This way, you can define the right level of change — coarse changes where you want consistency, granular tweaks where you need precision.

# The 5 Types of Element Functions
In fact, ggplot2 provides five different element functions, each designed for a specific kind of component:

* `element_rect()` — for rectangular shapes like backgrounds
* `element_line()` — for lines such as axes or grid lines
* `element_text()` — for text elements like titles and labels
* `element_blank()` — removes the element entirely

`ggplot2` also has `element_grob()`, which is used internally or for very advanced custom graphics. For most plots, you won’t need it.

Not all `theme()` arguments use `element_*` functions. Those expect different kind of inputs: some use other functions like `margin()` and `unit()` to specify spacing, others take numeric vectors, strings, or logical values. If we counted correctly, `theme()` has 139 arguments, of which 77 take `element_*` functions.

# Theme Attribute Explorer

Plot elements are organized into five main groups: *axis*, *plot*, *panel*, *facet*, and *legend*. Each group contains many arguments, forming a deep hierarchy.

# Spacing & Sizing
Some `theme()` arguments require sizes defined with `unit()`. The function combines a number with a measurement unit, such as `"pt"` (points), `"cm"` (centimeters), or `"lines"` (line height).

Units can be absolute (e.g., `"pt"`, `"cm"`) or relative (e.g., `"lines"` relative to text, `"npc"` relative to the plotting area). This allows sizes to either stay fixed or scale flexibly with the layout.

Examples for arguments that take units are:

* `legend.spacing.x = unit(.3, "lines")` increases the horizontal space between legends
* `axis.ticks.length = unit(5, "pt")` sets the tick length to 5 points
* `panel.spacing = unit(0.05, "npc")` — sets spacing between facet panels to 5% of the total panel width

# Margins
Text elements, along with a few dedicated `theme()` arguments, accept a `margin()` object to control spacing around elements. Adjusting margins can help create breathing room around the plot or specific elements, improving overall readability. Note that `margin()` internally uses `unit()` to define these sizes. The default unit is `"pt"`.

The `margin()` function takes four values in clockwise order: `top`, `right`, `bottom`, `left`. A handy mnemonic to recall the order is:

"margins always bring TRouBLe"

# Positioning Elements
A group of `theme()` arguments take **strings** to define the position, location, or alignment of elements.

Some common options are:

* `plot.title.position = "plot"` aligns the title with the plot margin
* `legend.position = "top"` moves the legend above the plot
* `legend.direction = "horizontal"` arranges its items in a row
* `plot.tag.location = "panel"` places the tag inside the panel


Some great resources to help you get started:
https://www.dataviz-inspiration.com/ and https://www.data-to-viz.com/


